name: BRB
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioblend=1.2
  - configparser=5.3
  - editdistance=0.6
  - matplotlib=3.8
  - numpy=1.26
  - python=3.12
  - python-dateutil=2.8
  - pytz=2023
  - pandas=2.1
  - urllib3=1.26.15
  - chardet=5.2
  - requests=2.31
  - certifi=2023
  - pyyaml=6.0
