channels:
  - conda-forge
  - bioconda
dependencies:
  - bioblend
  - configparser
  - editdistance
  - matplotlib
  - numpy
  - python=3.10
  - python-dateutil
  - pytz
  - pandas
  - urllib3=1.26.15
  - chardet=4.0.0
  - requests=2.29.0
  - pyyaml
